import type {
  Division,
  Product,
  BlogPost,
  TimelineEvent,
  Certificate,
  NavItem,
  Stat,
} from '@/types';

export const NAV_ITEMS: NavItem[] = [
  { label: 'Home', labelAr: 'الرئيسية', href: '/' },
  { label: 'About Us', labelAr: 'من نحن', href: '/about' },
  { label: 'Our Divisions', labelAr: 'أقسامنا', href: '/divisions' },
  { label: 'Products', labelAr: 'المنتجات', href: '/products' },
  { label: 'Production', labelAr: 'الإنتاج', href: '/production' },
  { label: 'Blog', labelAr: 'المدونة', href: '/blog' },
  { label: 'Contact', labelAr: 'اتصل بنا', href: '/contact' },
];

export const STATS: Stat[] = [
  { value: 20, suffix: '+', label: 'Products', labelAr: 'منتج' },
  { value: 3, suffix: '', label: 'Business Divisions', labelAr: 'أقسام أعمال' },
  { value: 100, suffix: '+', label: 'Business Partners', labelAr: 'شركاء أعمال' },
  { value: 10, suffix: '+', label: 'Countries Served', labelAr: 'دولة' },
];

export const DIVISIONS: Division[] = [
  {
    slug: 'foods',
    name: 'ARKA Foods',
    nameAr: 'أركا للأغذية',
    tagline: 'Premium Food Export',
    taglineAr: 'تصدير الأغذية المتميزة',
    description:
      'ARKA Foods specializes in the export of high-quality fresh, frozen, and processed food products. From farm to port, we ensure every product meets international quality standards.',
    descriptionAr:
      'تتخصص أركا للأغذية في تصدير المنتجات الغذائية الطازجة والمجمدة والمصنعة عالية الجودة. من المزرعة إلى الميناء، نضمن أن كل منتج يلبي معايير الجودة الدولية.',
    features: [
      'Food Export',
      'Fresh Products',
      'Frozen Products',
      'Quality Assurance',
    ],
    featuresAr: [
      'تصدير الأغذية',
      'منتجات طازجة',
      'منتجات مجمدة',
      'ضمان الجودة',
    ],
    image:
      'https://6a43934894555f542c2eaddc.imgix.net/sandbox/transport-logistics-concept.jpg',
    icon: 'Wheat',
    color: 'from-green-500 to-blue-500',
  },
  {
    slug: 'trade',
    name: 'ARKA Trade',
    nameAr: 'أركا للتجارة',
    tagline: 'Global Trade & Logistics',
    taglineAr: 'التجارة واللوجستيات العالمية',
    description:
      'ARKA Trade handles import, export, and commercial partnerships across industrial and consumer products. We connect suppliers and buyers worldwide with seamless international logistics.',
    descriptionAr:
      'تتولى أركا للتجارة الاستيراد والتصدير والشراكات التجارية عبر المنتجات الصناعية والاستهلاكية. نربط الموردين والمشترين حول العالم بلوجستيات دولية سلسة.',
    features: [
      'Import & Export',
      'Industrial Products',
      'Commercial Partnerships',
      'International Logistics',
    ],
    featuresAr: [
      'الاستيراد والتصدير',
      'المنتجات الصناعية',
      'الشراكات التجارية',
      'اللوجستيات الدولية',
    ],
    image:
      'https://images.unsplash.com/photo-1494412651409-8963ce7935a7?w=1200&q=80',
    icon: 'Ship',
    color: 'from-blue-500 to-indigo-500',
  },
  {
    slug: 'farmer',
    name: 'ARKA Farmer',
    nameAr: 'أركا للمزارع',
    tagline: 'Agricultural Production',
    taglineAr: 'الإنتاج الزراعي',
    description:
      'ARKA Farmer manages the full agricultural cycle — from farming and harvesting to packaging and export. We cultivate quality from the soil up, ensuring export-grade produce.',
    descriptionAr:
      'تدير أركا للمزارع الدورة الزراعية الكاملة — من الزراعة والحصاد إلى التعبئة والتصدير. نزرع الجودة من التربة، ونضمن منتجات بدرجة التصدير.',
    features: [
      'Agricultural Production',
      'Farming & Harvest',
      'Packaging',
      'Export Quality',
    ],
    featuresAr: [
      'الإنتاج الزراعي',
      'الزراعة والحصاد',
      'التعبئة',
      'جودة التصدير',
    ],
    image:
      'https://6a43934894555f542c2eaddc.imgix.net/sandbox/farmer-harvesting-tomatoes-avocados-field.jpg',
    icon: 'Sprout',
    color: 'from-amber-500 to-green-500',
  },
];

export const PRODUCTS: Product[] = [
{
  id: '1',
  name: 'Broccoli',
  nameAr: 'بروكلي',
  slug: 'broccoli',
  category: 'Fresh Produce',
  categoryAr: 'المنتجات الطازجة',
  description: 'Premium fresh Egyptian broccoli carefully selected and packed for export markets with excellent quality and freshness.',
  descriptionAr: 'منتج مصري طازج عالي الجودة يتم اختياره وتعبئته بعناية لأسواق التصدير مع الحفاظ على النضارة والجودة.',
  image: 'https://6a43934894555f542c2eaddc.imgix.net/broccoli-closeup.avif',
  gallery: [
    'https://images.unsplash.com/photo-1501004318641-b39e6451bec6?w=800&q=80',
  ],
  specifications: [
    { label: 'Quality', value: 'Export Grade A' },
    { label: 'Freshness', value: 'Harvested Daily' },
    { label: 'Origin', value: 'Egypt' },
    { label: 'Packing', value: 'Export Standard' },
  ],
  packaging: '5kg / 10kg carton boxes',
  packagingAr: 'كراتين 5 كجم أو 10 كجم',
  origin: 'Egypt',
  originAr: 'مصر',
  availability: 'Seasonal',
  availabilityAr: 'حسب الموسم',
  exportMarkets: ['Europe', 'Middle East', 'Africa'],
  division: 'trade',
},

{
  id: '2',
  name: 'Cauliflower',
  nameAr: 'القرنبيط',
  slug: 'cauliflower',
  category: 'Fresh Produce',
  categoryAr: 'المنتجات الطازجة',
  description: 'Premium fresh Egyptian cauliflower carefully selected and packed for export markets with excellent quality and freshness.',
  descriptionAr: 'منتج مصري طازج عالي الجودة يتم اختياره وتعبئته بعناية لأسواق التصدير مع الحفاظ على النضارة والجودة.',
  image: 'https://6a43934894555f542c2eaddc.imgix.net/irene-kredenets-zNsSGYXaeP8-unsplash.avif',
  gallery: [
    'https://images.unsplash.com/photo-1501004318641-b39e6451bec6?w=800&q=80',
  ],
  specifications: [
    { label: 'Quality', value: 'Export Grade A' },
    { label: 'Freshness', value: 'Harvested Daily' },
    { label: 'Origin', value: 'Egypt' },
    { label: 'Packing', value: 'Export Standard' },
  ],
  packaging: '5kg / 10kg carton boxes',
  packagingAr: 'كراتين 5 كجم أو 10 كجم',
  origin: 'Egypt',
  originAr: 'مصر',
  availability: 'Seasonal',
  availabilityAr: 'حسب الموسم',
  exportMarkets: ['Europe', 'Middle East', 'Africa'],
  division: 'trade',
},

{
  id: '3',
  name: 'Cabbage',
  nameAr: 'الكرنب',
  slug: 'cabbage',
  category: 'Fresh Produce',
  categoryAr: 'المنتجات الطازجة',
  description: 'Premium fresh Egyptian cabbage carefully selected and packed for export markets with excellent quality and freshness.',
  descriptionAr: 'منتج مصري طازج عالي الجودة يتم اختياره وتعبئته بعناية لأسواق التصدير مع الحفاظ على النضارة والجودة.',
  image: 'https://6a43934894555f542c2eaddc.imgix.net/closeup-vertical-shot-cabbage-plant-field.avif',
  gallery: [
    'https://images.unsplash.com/photo-1501004318641-b39e6451bec6?w=800&q=80',
  ],
  specifications: [
    { label: 'Quality', value: 'Export Grade A' },
    { label: 'Freshness', value: 'Harvested Daily' },
    { label: 'Origin', value: 'Egypt' },
    { label: 'Packing', value: 'Export Standard' },
  ],
  packaging: '5kg / 10kg carton boxes',
  packagingAr: 'كراتين 5 كجم أو 10 كجم',
  origin: 'Egypt',
  originAr: 'مصر',
  availability: 'Seasonal',
  availabilityAr: 'حسب الموسم',
  exportMarkets: ['Europe', 'Middle East', 'Africa'],
  division: 'trade',
},

{
  id: '4',
  name: 'Green Beans',
  nameAr: 'الفاصوليا الخضراء',
  slug: 'green-beans',
  category: 'Fresh Produce',
  categoryAr: 'المنتجات الطازجة',
  description: 'Premium fresh Egyptian green beans carefully selected and packed for export markets with excellent quality and freshness.',
  descriptionAr: 'منتج مصري طازج عالي الجودة يتم اختياره وتعبئته بعناية لأسواق التصدير مع الحفاظ على النضارة والجودة.',
  image: 'https://6a43934894555f542c2eaddc.imgix.net/high-angle-pea-pods-table.avif',
  gallery: [
    'https://images.unsplash.com/photo-1501004318641-b39e6451bec6?w=800&q=80',
  ],
  specifications: [
    { label: 'Quality', value: 'Export Grade A' },
    { label: 'Freshness', value: 'Harvested Daily' },
    { label: 'Origin', value: 'Egypt' },
    { label: 'Packing', value: 'Export Standard' },
  ],
  packaging: '5kg / 10kg carton boxes',
  packagingAr: 'كراتين 5 كجم أو 10 كجم',
  origin: 'Egypt',
  originAr: 'مصر',
  availability: 'Seasonal',
  availabilityAr: 'حسب الموسم',
  exportMarkets: ['Europe', 'Middle East', 'Africa'],
  division: 'trade',
},

{
  id: '5',
  name: 'Carrot',
  nameAr: 'الجزر',
  slug: 'carrot',
  category: 'Fresh Produce',
  categoryAr: 'المنتجات الطازجة',
  description: 'Premium fresh Egyptian carrot carefully selected and packed for export markets with excellent quality and freshness.',
  descriptionAr: 'منتج مصري طازج عالي الجودة يتم اختياره وتعبئته بعناية لأسواق التصدير مع الحفاظ على النضارة والجودة.',
  image: 'https://6a43934894555f542c2eaddc.imgix.net/stack-carrots-tray-marble-surface.avif',
  gallery: [
    'https://images.unsplash.com/photo-1501004318641-b39e6451bec6?w=800&q=80',
  ],
  specifications: [
    { label: 'Quality', value: 'Export Grade A' },
    { label: 'Freshness', value: 'Harvested Daily' },
    { label: 'Origin', value: 'Egypt' },
    { label: 'Packing', value: 'Export Standard' },
  ],
  packaging: '5kg / 10kg carton boxes',
  packagingAr: 'كراتين 5 كجم أو 10 كجم',
  origin: 'Egypt',
  originAr: 'مصر',
  availability: 'Seasonal',
  availabilityAr: 'حسب الموسم',
  exportMarkets: ['Europe', 'Middle East', 'Africa'],
  division: 'trade',
},

{
  id: '6',
  name: 'Potatoes',
  nameAr: 'البطاطس',
  slug: 'potatoes',
  category: 'Fresh Produce',
  categoryAr: 'المنتجات الطازجة',
  description: 'Premium fresh Egyptian potatoes carefully selected and packed for export markets with excellent quality and freshness.',
  descriptionAr: 'منتج مصري طازج عالي الجودة يتم اختياره وتعبئته بعناية لأسواق التصدير مع الحفاظ على النضارة والجودة.',
  image: 'https://6a43934894555f542c2eaddc.imgix.net/side-view-raw-potatoes-dish.avif',
  gallery: [
    'https://images.unsplash.com/photo-1501004318641-b39e6451bec6?w=800&q=80',
  ],
  specifications: [
    { label: 'Quality', value: 'Export Grade A' },
    { label: 'Freshness', value: 'Harvested Daily' },
    { label: 'Origin', value: 'Egypt' },
    { label: 'Packing', value: 'Export Standard' },
  ],
  packaging: '5kg / 10kg carton boxes',
  packagingAr: 'كراتين 5 كجم أو 10 كجم',
  origin: 'Egypt',
  originAr: 'مصر',
  availability: 'Seasonal',
  availabilityAr: 'حسب الموسم',
  exportMarkets: ['Europe', 'Middle East', 'Africa'],
  division: 'trade',
},

{
  id: '7',
  name: 'Onion',
  nameAr: 'البصل',
  slug: 'onion',
  category: 'Fresh Produce',
  categoryAr: 'المنتجات الطازجة',
  description: 'Premium fresh Egyptian onion carefully selected and packed for export markets with excellent quality and freshness.',
  descriptionAr: 'منتج مصري طازج عالي الجودة يتم اختياره وتعبئته بعناية لأسواق التصدير مع الحفاظ على النضارة والجودة.',
  image: 'https://6a43934894555f542c2eaddc.imgix.net/top-view-basket-full-onions-sackcloth-white-background.avif',
  gallery: [
    'https://images.unsplash.com/photo-1501004318641-b39e6451bec6?w=800&q=80',
  ],
  specifications: [
    { label: 'Quality', value: 'Export Grade A' },
    { label: 'Freshness', value: 'Harvested Daily' },
    { label: 'Origin', value: 'Egypt' },
    { label: 'Packing', value: 'Export Standard' },
  ],
  packaging: '5kg / 10kg carton boxes',
  packagingAr: 'كراتين 5 كجم أو 10 كجم',
  origin: 'Egypt',
  originAr: 'مصر',
  availability: 'Seasonal',
  availabilityAr: 'حسب الموسم',
  exportMarkets: ['Europe', 'Middle East', 'Africa'],
  division: 'trade',
},

{
  id: '8',
  name: 'Green Peas',
  nameAr: 'البازلاء',
  slug: 'green-peas',
  category: 'Fresh Produce',
  categoryAr: 'المنتجات الطازجة',
  description: 'Premium fresh Egyptian green peas carefully selected and packed for export markets with excellent quality and freshness.',
  descriptionAr: 'منتج مصري طازج عالي الجودة يتم اختياره وتعبئته بعناية لأسواق التصدير مع الحفاظ على النضارة والجودة.',
  image: 'https://6a43934894555f542c2eaddc.imgix.net/high-angle-shot-fresh-green-peas-wooden-table.avif',
  gallery: [
    'https://images.unsplash.com/photo-1501004318641-b39e6451bec6?w=800&q=80',
  ],
  specifications: [
    { label: 'Quality', value: 'Export Grade A' },
    { label: 'Freshness', value: 'Harvested Daily' },
    { label: 'Origin', value: 'Egypt' },
    { label: 'Packing', value: 'Export Standard' },
  ],
  packaging: '5kg / 10kg carton boxes',
  packagingAr: 'كراتين 5 كجم أو 10 كجم',
  origin: 'Egypt',
  originAr: 'مصر',
  availability: 'Seasonal',
  availabilityAr: 'حسب الموسم',
  exportMarkets: ['Europe', 'Middle East', 'Africa'],
  division: 'trade',
},

{
  id: '9',
  name: 'Okra',
  nameAr: 'البامية',
  slug: 'okra',
  category: 'Fresh Produce',
  categoryAr: 'المنتجات الطازجة',
  description: 'Premium fresh Egyptian okra carefully selected and packed for export markets with excellent quality and freshness.',
  descriptionAr: 'منتج مصري طازج عالي الجودة يتم اختياره وتعبئته بعناية لأسواق التصدير مع الحفاظ على النضارة والجودة.',
  image: 'https://images.unsplash.com/photo-1501004318641-b39e6451bec6?w=800&q=80',
  gallery: [
    'https://images.unsplash.com/photo-1501004318641-b39e6451bec6?w=800&q=80',
  ],
  specifications: [
    { label: 'Quality', value: 'Export Grade A' },
    { label: 'Freshness', value: 'Harvested Daily' },
    { label: 'Origin', value: 'Egypt' },
    { label: 'Packing', value: 'Export Standard' },
  ],
  packaging: '5kg / 10kg carton boxes',
  packagingAr: 'كراتين 5 كجم أو 10 كجم',
  origin: 'Egypt',
  originAr: 'مصر',
  availability: 'Seasonal',
  availabilityAr: 'حسب الموسم',
  exportMarkets: ['Europe', 'Middle East', 'Africa'],
  division: 'trade',
},

{
  id: '10',
  name: 'Mulukhiyah',
  nameAr: 'الملوخية',
  slug: 'mulukhiyah',
  category: 'Fresh Produce',
  categoryAr: 'المنتجات الطازجة',
  description: 'Premium fresh Egyptian mulukhiyah carefully selected and packed for export markets with excellent quality and freshness.',
  descriptionAr: 'منتج مصري طازج عالي الجودة يتم اختياره وتعبئته بعناية لأسواق التصدير مع الحفاظ على النضارة والجودة.',
  image: 'https://images.unsplash.com/photo-1501004318641-b39e6451bec6?w=800&q=80',
  gallery: [
    'https://images.unsplash.com/photo-1501004318641-b39e6451bec6?w=800&q=80',
  ],
  specifications: [
    { label: 'Quality', value: 'Export Grade A' },
    { label: 'Freshness', value: 'Harvested Daily' },
    { label: 'Origin', value: 'Egypt' },
    { label: 'Packing', value: 'Export Standard' },
  ],
  packaging: '5kg / 10kg carton boxes',
  packagingAr: 'كراتين 5 كجم أو 10 كجم',
  origin: 'Egypt',
  originAr: 'مصر',
  availability: 'Seasonal',
  availabilityAr: 'حسب الموسم',
  exportMarkets: ['Europe', 'Middle East', 'Africa'],
  division: 'trade',
},

{
  id: '11',
  name: 'Orange',
  nameAr: 'البرتقال',
  slug: 'orange',
  category: 'Fresh Produce',
  categoryAr: 'المنتجات الطازجة',
  description: 'Premium fresh Egyptian orange carefully selected and packed for export markets with excellent quality and freshness.',
  descriptionAr: 'منتج مصري طازج عالي الجودة يتم اختياره وتعبئته بعناية لأسواق التصدير مع الحفاظ على النضارة والجودة.',
  image: 'https://images.unsplash.com/photo-1501004318641-b39e6451bec6?w=800&q=80',
  gallery: [
    'https://images.unsplash.com/photo-1501004318641-b39e6451bec6?w=800&q=80',
  ],
  specifications: [
    { label: 'Quality', value: 'Export Grade A' },
    { label: 'Freshness', value: 'Harvested Daily' },
    { label: 'Origin', value: 'Egypt' },
    { label: 'Packing', value: 'Export Standard' },
  ],
  packaging: '5kg / 10kg carton boxes',
  packagingAr: 'كراتين 5 كجم أو 10 كجم',
  origin: 'Egypt',
  originAr: 'مصر',
  availability: 'Seasonal',
  availabilityAr: 'حسب الموسم',
  exportMarkets: ['Europe', 'Middle East', 'Africa'],
  division: 'trade',
},

{
  id: '12',
  name: 'Strawberry',
  nameAr: 'الفراولة',
  slug: 'strawberry',
  category: 'Fresh Produce',
  categoryAr: 'المنتجات الطازجة',
  description: 'Premium fresh Egyptian strawberry carefully selected and packed for export markets with excellent quality and freshness.',
  descriptionAr: 'منتج مصري طازج عالي الجودة يتم اختياره وتعبئته بعناية لأسواق التصدير مع الحفاظ على النضارة والجودة.',
  image: 'https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=800&q=80',
  gallery: [
    'https://images.unsplash.com/photo-1501004318641-b39e6451bec6?w=800&q=80',
  ],
  specifications: [
    { label: 'Quality', value: 'Export Grade A' },
    { label: 'Freshness', value: 'Harvested Daily' },
    { label: 'Origin', value: 'Egypt' },
    { label: 'Packing', value: 'Export Standard' },
  ],
  packaging: '5kg / 10kg carton boxes',
  packagingAr: 'كراتين 5 كجم أو 10 كجم',
  origin: 'Egypt',
  originAr: 'مصر',
  availability: 'Seasonal',
  availabilityAr: 'حسب الموسم',
  exportMarkets: ['Europe', 'Middle East', 'Africa'],
  division: 'trade',
},

{
  id: '13',
  name: 'Pomegranate',
  nameAr: 'الرمان',
  slug: 'pomegranate',
  category: 'Fresh Produce',
  categoryAr: 'المنتجات الطازجة',
  description: 'Premium fresh Egyptian pomegranate carefully selected and packed for export markets with excellent quality and freshness.',
  descriptionAr: 'منتج مصري طازج عالي الجودة يتم اختياره وتعبئته بعناية لأسواق التصدير مع الحفاظ على النضارة والجودة.',
  image: 'https://images.unsplash.com/photo-1501004318641-b39e6451bec6?w=800&q=80',
  gallery: [
    'https://images.unsplash.com/photo-1501004318641-b39e6451bec6?w=800&q=80',
  ],
  specifications: [
    { label: 'Quality', value: 'Export Grade A' },
    { label: 'Freshness', value: 'Harvested Daily' },
    { label: 'Origin', value: 'Egypt' },
    { label: 'Packing', value: 'Export Standard' },
  ],
  packaging: '5kg / 10kg carton boxes',
  packagingAr: 'كراتين 5 كجم أو 10 كجم',
  origin: 'Egypt',
  originAr: 'مصر',
  availability: 'Seasonal',
  availabilityAr: 'حسب الموسم',
  exportMarkets: ['Europe', 'Middle East', 'Africa'],
  division: 'trade',
},

{
  id: '14',
  name: 'Mango',
  nameAr: 'المانجو',
  slug: 'mango',
  category: 'Fresh Produce',
  categoryAr: 'المنتجات الطازجة',
  description: 'Premium fresh Egyptian mango carefully selected and packed for export markets with excellent quality and freshness.',
  descriptionAr: 'منتج مصري طازج عالي الجودة يتم اختياره وتعبئته بعناية لأسواق التصدير مع الحفاظ على النضارة والجودة.',
  image: 'https://images.unsplash.com/photo-1501004318641-b39e6451bec6?w=800&q=80',
  gallery: [
    'https://images.unsplash.com/photo-1501004318641-b39e6451bec6?w=800&q=80',
  ],
  specifications: [
    { label: 'Quality', value: 'Export Grade A' },
    { label: 'Freshness', value: 'Harvested Daily' },
    { label: 'Origin', value: 'Egypt' },
    { label: 'Packing', value: 'Export Standard' },
  ],
  packaging: '5kg / 10kg carton boxes',
  packagingAr: 'كراتين 5 كجم أو 10 كجم',
  origin: 'Egypt',
  originAr: 'مصر',
  availability: 'Seasonal',
  availabilityAr: 'حسب الموسم',
  exportMarkets: ['Europe', 'Middle East', 'Africa'],
  division: 'trade',
},

{
  id: '15',
  name: 'Grapes',
  nameAr: 'العنب',
  slug: 'grapes',
  category: 'Fresh Produce',
  categoryAr: 'المنتجات الطازجة',
  description: 'Premium fresh Egyptian grapes carefully selected and packed for export markets with excellent quality and freshness.',
  descriptionAr: 'منتج مصري طازج عالي الجودة يتم اختياره وتعبئته بعناية لأسواق التصدير مع الحفاظ على النضارة والجودة.',
  image: 'https://images.unsplash.com/photo-1501004318641-b39e6451bec6?w=800&q=80',
  gallery: [
    'https://images.unsplash.com/photo-1501004318641-b39e6451bec6?w=800&q=80',
  ],
  specifications: [
    { label: 'Quality', value: 'Export Grade A' },
    { label: 'Freshness', value: 'Harvested Daily' },
    { label: 'Origin', value: 'Egypt' },
    { label: 'Packing', value: 'Export Standard' },
  ],
  packaging: '5kg / 10kg carton boxes',
  packagingAr: 'كراتين 5 كجم أو 10 كجم',
  origin: 'Egypt',
  originAr: 'مصر',
  availability: 'Seasonal',
  availabilityAr: 'حسب الموسم',
  exportMarkets: ['Europe', 'Middle East', 'Africa'],
  division: 'trade',
},

{
  id: '16',
  name: 'Guava',
  nameAr: 'الجوافة',
  slug: 'guava',
  category: 'Fresh Produce',
  categoryAr: 'المنتجات الطازجة',
  description: 'Premium fresh Egyptian guava carefully selected and packed for export markets with excellent quality and freshness.',
  descriptionAr: 'منتج مصري طازج عالي الجودة يتم اختياره وتعبئته بعناية لأسواق التصدير مع الحفاظ على النضارة والجودة.',
  image: 'https://images.unsplash.com/photo-1501004318641-b39e6451bec6?w=800&q=80',
  gallery: [
    'https://images.unsplash.com/photo-1501004318641-b39e6451bec6?w=800&q=80',
  ],
  specifications: [
    { label: 'Quality', value: 'Export Grade A' },
    { label: 'Freshness', value: 'Harvested Daily' },
    { label: 'Origin', value: 'Egypt' },
    { label: 'Packing', value: 'Export Standard' },
  ],
  packaging: '5kg / 10kg carton boxes',
  packagingAr: 'كراتين 5 كجم أو 10 كجم',
  origin: 'Egypt',
  originAr: 'مصر',
  availability: 'Seasonal',
  availabilityAr: 'حسب الموسم',
  exportMarkets: ['Europe', 'Middle East', 'Africa'],
  division: 'trade',
},
];

export const PRODUCT_CATEGORIES = [
  'All',
  'Grains',
  'Frozen',
  'Fresh',
  'Oils',
  'Spices & Herbs',
  'Commodities',
];

export const PRODUCT_CATEGORIES_AR = [
  'الكل',
  'الحبوب',
  'مجمد',
  'طازج',
  'الزيوت',
  'توابل وأعشاب',
  'السلع',
];

export const BLOG_POSTS: BlogPost[] = [
  {
    slug: 'export-tips-for-egyptian-agriculture',
    title: '10 Essential Export Tips for Egyptian Agricultural Products',
    titleAr: '10 نصائح أساسية لتصدير المنتجات الزراعية المصرية',
    excerpt:
      'Learn the key strategies for successfully exporting Egyptian agricultural products to international markets, from quality control to documentation.',
    excerptAr:
      'تعرف على الاستراتيجيات الأساسية لتصدير المنتجات الزراعية المصرية بنجاح إلى الأسواق الدولية، من مراقبة الجودة إلى الوثائق.',
    content:
      'Exporting Egyptian agricultural products requires careful planning and execution. Here are ten essential tips to ensure success in international markets...',
    contentAr:
      'يتطلب تصدير المنتجات الزراعية المصرية تخطيطاً وتنفيذاً دقيقاً. إليك عشر نصائح أساسية لضمان النجاح في الأسواق الدولية...',
    image: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=1200&q=80',
    author: 'Ahmed Hassan',
    authorAr: 'أحمد حسن',
    date: '2024-03-15',
    readingTime: 8,
    category: 'Export Tips',
    categoryAr: 'نصائح التصدير',
    tags: ['Export', 'Agriculture', 'Egypt', 'Tips'],
    featured: true,
  },
  {
    slug: 'sustainable-farming-practices',
    title: 'Sustainable Farming: The Future of Egyptian Agriculture',
    titleAr: 'الزراعة المستدامة: مستقبل الزراعة المصرية',
    excerpt:
      'How sustainable farming practices are transforming Egyptian agriculture and creating new opportunities for export-quality produce.',
    excerptAr:
      'كيف تحول ممارسات الزراعة المستدامة الزراعة المصرية وتخلق فرصاً جديدة للمنتجات بجودة التصدير.',
    content:
      'Sustainable farming is no longer just a buzzword — it is becoming the standard for agricultural production worldwide...',
    contentAr:
      'لم تعد الزراعة المستدامة مجرد كلمة رنانة — بل أصبحت المعيار للإنتاج الزراعي في جميع أنحاء العالم...',
    image: 'https://images.unsplash.com/photo-1500382017468-9049fed74794?w=1200&q=80',
    author: 'Sarah Ibrahim',
    authorAr: 'سارة إبراهيم',
    date: '2024-03-10',
    readingTime: 6,
    category: 'Agriculture News',
    categoryAr: 'أخبار الزراعة',
    tags: ['Sustainability', 'Farming', 'Agriculture'],
  },
  {
    slug: 'global-food-industry-trends-2024',
    title: 'Global Food Industry Trends Shaping 2024',
    titleAr: 'اتجاهات صناعة الأغذية العالمية التي تشكل عام 2024',
    excerpt:
      'From plant-based foods to sustainable packaging, explore the trends that are reshaping the global food industry this year.',
    excerptAr:
      'من الأغذية النباتية إلى التعبئة المستدامة، استكشف الاتجاهات التي تعيد تشكيل صناعة الأغذية العالمية هذا العام.',
    content:
      'The global food industry is undergoing rapid transformation. Several key trends are emerging that will shape the market in 2024 and beyond...',
    contentAr:
      'تشهد صناعة الأغذية العالمية تحولاً سريعاً. تظهر عدة اتجاهات رئيسية ستشكل السوق في عام 2024 وما بعده...',
    image: 'https://images.unsplash.com/photo-1542838132-25c8eb9396f4?w=1200&q=80',
    author: 'Mohamed Farouk',
    authorAr: 'محمد فاروق',
    date: '2024-03-05',
    readingTime: 7,
    category: 'Food Industry',
    categoryAr: 'صناعة الأغذية',
    tags: ['Food', 'Trends', 'Industry', '2024'],
  },
  {
    slug: 'navigating-international-markets',
    title: 'Navigating International Markets: A Guide for Exporters',
    titleAr: 'التنقل في الأسواق الدولية: دليل للمصدرين',
    excerpt:
      'Understanding market entry strategies, trade agreements, and cultural considerations when expanding into new international markets.',
    excerptAr:
      'فهم استراتيجيات دخول السوق والاتفاقيات التجارية والاعتبارات الثقافية عند التوسع في أسواق دولية جديدة.',
    content:
      'Expanding into international markets is a significant step for any export business. Understanding the nuances of each market is crucial...',
    contentAr:
      'التوسع في الأسواق الدولية خطوة مهمة لأي عمل تجاري تصديري. فهم تفاصيل كل سوق أمر بالغ الأهمية...',
    image: 'https://images.unsplash.com/photo-1494412651409-8963ce7935a7?w=1200&q=80',
    author: 'Layla Mostafa',
    authorAr: 'ليلى مصطفى',
    date: '2024-02-28',
    readingTime: 9,
    category: 'International Markets',
    categoryAr: 'الأسواق الدولية',
    tags: ['Markets', 'Export', 'Trade', 'Guide'],
  },
  {
    slug: 'import-regulations-update',
    title: 'Key Import Regulations You Need to Know in 2024',
    titleAr: 'لوائح الاستيراد الرئيسية التي تحتاج لمعرفتها في 2024',
    excerpt:
      'Stay compliant with the latest import regulations across major markets including the EU, US, and Gulf countries.',
    excerptAr:
      'ابقَ متوافقاً مع أحدث لوائح الاستيراد عبر الأسواق الرئيسية بما في ذلك الاتحاد الأوروبي والولايات المتحدة ودول الخليج.',
    content:
      'Import regulations are constantly evolving. Staying up-to-date with the latest requirements is essential for smooth trade operations...',
    contentAr:
      'لوائح الاستيراد تتطور باستمرار. البقاء على اطلاع بأحدث المتطلبات أمر ضروري لعمليات تجارية سلسة...',
    image: 'https://images.unsplash.com/photo-1450101499163-884d2fca9d9d?w=1200&q=80',
    author: 'Karim Abdelrahman',
    authorAr: 'كريم عبد الرحمن',
    date: '2024-02-20',
    readingTime: 5,
    category: 'Import Regulations',
    categoryAr: 'لوائح الاستيراد',
    tags: ['Import', 'Regulations', 'Compliance', '2024'],
  },
  {
    slug: 'shipping-updates-supply-chain',
    title: 'Shipping Updates: Global Supply Chain in 2024',
    titleAr: 'تحديثات الشحن: سلسلة التوريد العالمية في 2024',
    excerpt:
      'The latest developments in global shipping, freight rates, and supply chain logistics affecting import-export businesses.',
    excerptAr:
      'أحدث التطورات في الشحن العالمي وأسعار الشحن ولوجستيات سلسلة التوريد التي تؤثر على أعمال الاستيراد والتصدير.',
    content:
      'The global shipping industry continues to face challenges and opportunities. Understanding current trends helps businesses plan effectively...',
    contentAr:
      'تواجه صناعة الشحن العالمية تحديات وفرصاً مستمرة. فهم الاتجاهات الحالية يساعد الشركات على التخطيط بفعالية...',
    image: 'https://images.unsplash.com/photo-1494412519320-aa613dfb7738?w=1200&q=80',
    author: 'Omar Saeed',
    authorAr: 'عمر سعيد',
    date: '2024-02-15',
    readingTime: 6,
    category: 'Shipping Updates',
    categoryAr: 'تحديثات الشحن',
    tags: ['Shipping', 'Logistics', 'Supply Chain'],
  },
  {
    slug: 'trade-insights-middle-east',
    title: 'Trade Insights: Middle East Market Opportunities',
    titleAr: 'رؤى تجارية: فرص سوق الشرق الأوسط',
    excerpt:
      'An in-depth analysis of trade opportunities in the Middle East and how Egyptian exporters can capitalize on them.',
    excerptAr:
      'تحليل متعمق للفرص التجارية في الشرق الأوسط وكيف يمكن للمصدرين المصريين الاستفادة منها.',
    content:
      'The Middle East represents a significant market opportunity for Egyptian exporters. With growing populations and increasing food demand...',
    contentAr:
      'يمثل الشرق الأوسط فرصة سوقية كبيرة للمصدرين المصريين. مع تزايد السكان والطلب المتزايد على الأغذية...',
    image: 'https://images.unsplash.com/photo-1494412651409-8963ce7935a7?w=1200&q=80',
    author: 'Nour El-Din',
    authorAr: 'نور الدين',
    date: '2024-02-10',
    readingTime: 8,
    category: 'Trade Insights',
    categoryAr: 'رؤى تجارية',
    tags: ['Trade', 'Middle East', 'Market', 'Insights'],
  },
  {
    slug: 'export-regulations-phytosanitary',
    title: 'Understanding Export Regulations and Phytosanitary Certificates',
    titleAr: 'فهم لوائح التصدير والشهادات الصحية النباتية',
    excerpt:
      'A comprehensive guide to export documentation, phytosanitary certificates, and compliance requirements for agricultural products.',
    excerptAr:
      'دليل شامل لوثائق التصدير والشهادات الصحية النباتية ومتطلبات الامتثال للمنتجات الزراعية.',
    content:
      'Proper documentation is the backbone of successful agricultural exports. Phytosanitary certificates ensure products meet the health standards...',
    contentAr:
      'الوثائق المناسبة هي العمود الفقري للتصدير الزراعي الناجح. تضمن الشهادات الصحية النباتية أن المنتجات تلبي معايير الصحة...',
    image: 'https://images.unsplash.com/photo-1450101499163-884d2fca9d9d?w=1200&q=80',
    author: 'Ahmed Hassan',
    authorAr: 'أحمد حسن',
    date: '2024-02-05',
    readingTime: 7,
    category: 'Export Regulations',
    categoryAr: 'لوائح التصدير',
    tags: ['Export', 'Regulations', 'Phytosanitary', 'Documentation'],
  },
];

export const BLOG_CATEGORIES = [
  'All',
  'Export Tips',
  'Agriculture News',
  'Food Industry',
  'International Markets',
  'Import Regulations',
  'Export Regulations',
  'Shipping Updates',
  'Trade Insights',
];

export const BLOG_CATEGORIES_AR = [
  'الكل',
  'نصائح التصدير',
  'أخبار الزراعة',
  'صناعة الأغذية',
  'الأسواق الدولية',
  'لوائح الاستيراد',
  'لوائح التصدير',
  'تحديثات الشحن',
  'رؤى تجارية',
];

export const TIMELINE: TimelineEvent[] = [
  {
    year: '2015',
    title: 'Foundation',
    titleAr: 'التأسيس',
    description: 'ARKA was founded in Cairo, Egypt, with a vision to connect Egyptian agriculture to the world.',
    descriptionAr: 'تأسست أركا في القاهرة، مصر، برؤية ربط الزراعة المصرية بالعالم.',
  },
  {
    year: '2017',
    title: 'First Export Shipment',
    titleAr: 'أول شحنة تصدير',
    description: 'Successfully completed our first major export shipment to European markets.',
    descriptionAr: 'أكملنا بنجاح أول شحنة تصدير رئيسية إلى الأسواق الأوروبية.',
  },
  {
    year: '2019',
    title: 'ARKA Foods Division',
    titleAr: 'قسم أركا للأغذية',
    description: 'Launched ARKA Foods division, specializing in fresh and frozen food exports.',
    descriptionAr: 'أطلقنا قسم أركا للأغذية، المتخصص في تصدير الأغذية الطازجة والمجمدة.',
  },
  {
    year: '2021',
    title: 'ARKA Trade Division',
    titleAr: 'قسم أركا للتجارة',
    description: 'Expanded with ARKA Trade, handling import, export, and international logistics.',
    descriptionAr: 'توسعنا مع أركا للتجارة، للتعامل مع الاستيراد والتصدير واللوجستيات الدولية.',
  },
  {
    year: '2022',
    title: 'ARKA Farmer Division',
    titleAr: 'قسم أركا للمزارع',
    description: 'Established ARKA Farmer to manage the full agricultural production cycle.',
    descriptionAr: 'أنشأنا أركا للمزارع لإدارة الدورة الزراعية الكاملة.',
  },
  {
    year: '2024',
    title: 'Global Expansion',
    titleAr: 'التوسع العالمي',
    description: 'Now serving 10+ countries with 100+ business partners across three divisions.',
    descriptionAr: 'نخدم الآن أكثر من 10 دول مع أكثر من 100 شريك تجاري عبر ثلاثة أقسام.',
  },
];

export const CERTIFICATES: Certificate[] = [
  {
    name: 'ISO 22000',
    nameAr: 'ISO 22000',
    description: 'Food Safety Management System certification',
    descriptionAr: 'شهادة نظام إدارة سلامة الأغذية',
    image: 'https://images.unsplash.com/photo-1450101499163-884d2fca9d9d?w=400&q=80',
  },
  {
    name: 'HACCP',
    nameAr: 'HACCP',
    description: 'Hazard Analysis Critical Control Point certified',
    descriptionAr: 'شهادة تحليل المخاطر ونقاط التحكم الحرجة',
    image: 'https://images.unsplash.com/photo-1450101499163-884d2fca9d9d?w=400&q=80',
  },
  {
    name: 'Global G.A.P.',
    nameAr: 'Global G.A.P.',
    description: 'Good Agricultural Practices certification',
    descriptionAr: 'شهادة الممارسات الزراعية الجيدة',
    image: 'https://images.unsplash.com/photo-1450101499163-884d2fca9d9d?w=400&q=80',
  },
  {
    name: 'BRC',
    nameAr: 'BRC',
    description: 'British Retail rtium food safety standard',
    descriptionAr: 'معيار سلامة الأغذية للاتحاد البريطاني للتجزئة',
    image: 'https://images.unsplash.com/photo-1450101499163-884d2fca9d9d?w=400&q=80',
  },
  {
    name: 'HALAL',
    nameAr: 'HALAL',
    description: 'Halal certification for food products',
    descriptionAr: 'شهادة الحلال للمنتجات الغذائية',
    image: 'https://images.unsplash.com/photo-1450101499163-884d2fca9d9d?w=400&q=80',
  },
  {
    name: 'FDA Registered',
    nameAr: 'مسجل FDA',
    description: 'US Food and Drug Administration registered',
    descriptionAr: 'مسجل لدى إدارة الغذاء والدواء الأمريكية',
    image: 'https://images.unsplash.com/photo-1450101499163-884d2fca9d9d?w=400&q=80',
  },
];

export const PRODUCTION_STEPS = [
  {
    title: 'Farming',
    titleAr: 'الزراعة',
    description: 'Carefully selected seeds are planted using sustainable agricultural practices across our partner farms.',
    descriptionAr: 'تُزرع بذور مختارة بعناية باستخدام ممارسات زراعية مستدامة عبر مزارعنا الشريكة.',
    icon: 'Sprout',
    image: 'https://images.unsplash.com/photo-1500382017468-9049fed74794?w=800&q=80',
  },
  {
    title: 'Harvesting',
    titleAr: 'الحصاد',
    description: 'Crops are harvested at peak ripeness using modern machinery to ensure quality and minimize waste.',
    descriptionAr: 'تُحصد المحاصيل في ذروة النضج باستخدام آلات حديثة لضمان الجودة وتقليل الهدر.',
    icon: 'Wheat',
    image: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=800&q=80',
  },
  {
    title: 'Processing',
    titleAr: 'المعالجة',
    description: 'Raw produce is cleaned, sorted, and processed in our state-of-the-art facilities.',
    descriptionAr: 'تُنظف وتُفرز وتُعالج المنتجات الخام في مرافقنا المتطورة.',
    icon: 'Factory',
    image: 'https://images.unsplash.com/photo-1518977676601-b53f82aba6b5?w=800&q=80',
  },
  {
    title: 'Quality Control',
    titleAr: 'مراقبة الجودة',
    description: 'Every batch undergoes rigorous quality testing in our certified laboratories.',
    descriptionAr: 'تخضع كل دفعة لاختبارات جودة صارمة في مختبراتنا المعتمدة.',
    icon: 'ShieldCheck',
    image: 'https://images.unsplash.com/photo-1450101499163-884d2fca9d9d?w=800&q=80',
  },
  {
    title: 'Packaging',
    titleAr: 'التعبئة',
    description: 'Products are packaged in food-grade materials with full traceability and labeling.',
    descriptionAr: 'تُعبأ المنتجات في مواد درجة الغذاء مع تتبع كامل ووضع العلامات.',
    icon: 'Package',
    image: 'https://images.unsplash.com/photo-1607083206869-4c7672e72fac?w=800&q=80',
  },
  {
    title: 'Cold Storage',
    titleAr: 'التخزين البارد',
    description: 'Temperature-controlled storage facilities maintain product freshness and extend shelf life.',
    descriptionAr: 'مرافق تخزين بدرجة حرارة محكومة تحافظ على طزاجة المنتج وتطيل عمر التخزين.',
    icon: 'Snowflake',
    image: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=800&q=80',
  },
  {
    title: 'Shipping',
    titleAr: 'الشحن',
    description: 'Efficient logistics network ensures timely delivery to ports worldwide.',
    descriptionAr: 'شبكة لوجستية فعالة تضمن التسليم في الوقت المناسب إلى الموانئ حول العالم.',
    icon: 'Ship',
    image: 'https://images.unsplash.com/photo-1494412519320-aa613dfb7738?w=800&q=80',
  },
  {
    title: 'Export',
    titleAr: 'التصدير',
    description: 'Complete export documentation and customs clearance for smooth international trade.',
    descriptionAr: 'وثائق تصدير كاملة وتخليص جمركي للتجارة الدولية السلسة.',
    icon: 'Globe',
    image: 'https://images.unsplash.com/photo-1494412651409-8963ce7935a7?w=800&q=80',
  },
];

export const CORE_VALUES = [
  {
    title: 'Quality',
    titleAr: 'الجودة',
    description: 'We never compromise on quality. Every product meets international standards.',
    descriptionAr: 'لا نساوم على الجودة أبداً. كل منتج يلبي المعايير الدولية.',
    icon: 'ShieldCheck',
  },
  {
    title: 'Integrity',
    titleAr: 'النزاهة',
    description: 'Honest and transparent business practices in all our relationships.',
    descriptionAr: 'ممارسات تجارية صادقة وشفافة في جميع علاقاتنا.',
    icon: 'Heart',
  },
  {
    title: 'Innovation',
    titleAr: 'الابتكار',
    description: 'Continuously improving our processes and adopting new technologies.',
    descriptionAr: 'نحسن عملياتنا باستمرار ونتبنى تقنيات جديدة.',
    icon: 'Lightbulb',
  },
  {
    title: 'Sustainability',
    titleAr: 'الاستدامة',
    description: 'Committed to environmentally responsible agricultural and trade practices.',
    descriptionAr: 'ملتزمون بممارسات زراعية وتجارية مسؤولة بيئياً.',
    icon: 'Leaf',
  },
  {
    title: 'Partnership',
    titleAr: 'الشراكة',
    description: 'Building long-term relationships with farmers, suppliers, and clients.',
    descriptionAr: 'بناء علاقات طويلة الأمد مع المزارعين والموردين والعملاء.',
    icon: 'Handshake',
  },
  {
    title: 'Excellence',
    titleAr: 'التميز',
    description: 'Striving for excellence in every aspect of our operations.',
    descriptionAr: 'نسعى للتميز في كل جانب من جوانب عملياتنا.',
    icon: 'Award',
  },
];

export const FAQS = [
  {
    question: 'What products does ARKA export?',
    questionAr: 'ما هي المنتجات التي تصدرها أركا؟',
    answer: 'ARKA exports over 20 products including rice, sugar, frozen vegetables, fresh produce, olive oil, dates, herbs, spices, and more across our three divisions.',
    answerAr: 'تصدر أركا أكثر من 20 منتجاً بما في ذلك الأرز والسكر والخضروات المجمدة والمنتجات الطازجة وزيت الزيتون والتمر والأعشاب والتوابل والمزيد عبر أقسامنا الثلاثة.',
  },
  {
    question: 'Which countries does ARKA serve?',
    questionAr: 'ما هي الدول التي تخدمها أركا؟',
    answer: 'ARKA serves 10+ countries across Europe, the Middle East, Africa, Asia, and North America, with a growing network of business partners.',
    answerAr: 'تخدم أركا أكثر من 10 دول عبر أوروبا والشرق الأوسط وأفريقيا وآسيا وأمريكا الشمالية، مع شبكة متنامية من الشركاء التجاريين.',
  },
  {
    question: 'What certifications does ARKA hold?',
    questionAr: 'ما هي الشهادات التي تحملها أركا؟',
    answer: 'ARKA holds ISO 22000, HACCP, Global G.A.P., BRC, HALAL, and FDA registrations, ensuring our products meet the highest international standards.',
    answerAr: 'تحمل أركا شهادات ISO 22000 وHACCP وGlobal G.A.P. وBRC وHALAL وتسجيلات FDA، مما يضمن أن منتجاتنا تلبي أعلى المعايير الدولية.',
  },
  {
    question: 'How can I become a business partner?',
    questionAr: 'كيف يمكنني أن أصبح شريك تجاري؟',
    answer: 'You can reach out through our contact page or WhatsApp. Our team will respond within 24 hours to discuss partnership opportunities.',
    answerAr: 'يمكنك التواصل عبر صفحة الاتصال أو واتساب. سيرد فريقنا خلال 24 ساعة لمناقشة فرص الشراكة.',
  },
  {
    question: 'What is the minimum order quantity?',
    questionAr: 'ما هو الحد الأدنى لكمية الطلب؟',
    answer: 'Minimum order quantities vary by product. Please contact us with your specific requirements and we will provide detailed information.',
    answerAr: 'تختلف كميات الطلب الأدنى حسب المنتج. يرجى الاتصال بنا بمتطلباتك المحددة وسنقدم معلومات مفصلة.',
  },
  {
    question: 'Does ARKA provide custom packaging?',
    questionAr: 'هل توفر أركا تعبئة مخصصة؟',
    answer: 'Yes, we offer custom packaging solutions including private label options. Contact us to discuss your specific packaging needs.',
    answerAr: 'نعم، نقدم حلول تعبئة مخصصة بما في ذلك خيارات العلامات الخاصة. اتصل بنا لمناقشة احتياجات التعبئة المحددة.',
  },
];

export const COMPANY_INFO = {
  name: 'ARKA',
  fullName: 'ARKA Import & Export',
  fullNameAr: 'أركا للاستيراد والتصدير',
  tagline: 'Connecting Egypt to the World',
  taglineAr: 'نربط مصر بالعالم',
  phone: '+201006724853',
  whatsapp: '+201006724853',
  email: 'arkatrade@arkatrade.info',
  salesEmail: 'arkatrade@arkatrade.info',
  address: 'Itay El Barud, Beheira, Egypt',
  addressAr: 'بجوار البنزينة، اول طريق شنديد، ايتاي البارود، البحيرة، مصر',
  workingHours: 'Sunday - Thursday: 9:00 AM - 6:00 PM',
  workingHoursAr: 'الأحد - الخميس: 9:00 ص - 6:00 م',
  social: {
    linkedin: 'https://www.linkedin.com/company/arkatrade/',
    facebook: 'https://www.facebook.com/arkatrade1/',
    instagram: 'https://www.instagram.com/arka_trade1/',
    twitter: 'https://twitter.com/arkaexport',
  },
};

export const PARTNERS = [
  'Maersk',
  'DHL',
  'CMA CGM',
  'MSC',
  'Hapag-Lloyd',
  'Cosco',
  'Evergreen',
  'Yang Ming',
];
